#!/bin/bash

# Create a virtual network using network namespaces and veth pairs
# to connect them.
# Assuming $CONFIGDIR == "cfg":
# * Files in cfg/<Node name> will be overlaid over /etc, i.e. if a file with
# the same name exists in both directory, the one in cfg/<Node name> will
# be the one used.
# * If cfg/<Node name>_$BOOT (defaults to cfg/<Node name>_boot) exists and
# is executable, it will be executed when the node is created
# * If cfg/<Node name>_$STARTUP (defaults to cfg/<Node name>_start) exists and
# is executable, it will be executed when the whole network has started
#

# IMPORTANT NOTE: Node names MUST NOT exceed 9 characters.
# This is due to the limitation to 14 characters of interface names

# You can override any of these settings on a per-topology basis
# Group number
GROUPNUMBER=7
# Node configs
CONFIGDIR=grp7_cfg
# boot script name
BOOT="boot"
# startup script name
STARTUP="start"
PREFIXBASE="fde4:${GROUPNUMBER}"
PREFIXLEN=32
# You can reuse the above two to generate ip addresses/routes, ...
# e.g. "${PREFIXBASE}:1234::/$((PREFIXLEN+16))"

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"
    #
    #   PIERRE0---PIERRE1   ----------------   DJAF0----DJAF1
    #	    \    /                                 \     /
    #       PIERRE2                                 DJAF2
    #
    #          \   \                             /   /
    #           \   \                          /    /
    #            \   \                       /    /
    #             \   \                    /     /
    #              \   \                 /     /
    #               \   \              /      /
    #                \   \            /      /
    #                 \   \          /      /
    #                  \   \        /      /
    #                   \                 /
    #                    \    SAMIR0     /
    #                         /  |  \
    #                    SAMIR1--|-SAMIR2
    #                        \   |   /
    #                         SAMIR3
    #
    #
    #
    #              
    #
    #
    # Nodes are creadted on the fly, and their interface are assigned as
    # <node name>-eth<count>, where count starts at 0 and is increased by 1
    # after each new interface

	add_link SAMIR0 SAMIR1 
	add_link SAMIR0 SAMIR3

	add_link SAMIR1 PIERROT0
	add_link SAMIR1 PIERROT1 
	add_link SAMIR1 SAMIR2

	add_link SAMIR2 DJAF0
	add_link SAMIR2 DJAF1
	add_link SAMIR2 SAMIR3

	add_link PIERROT0 PIERROT2

	add_link PIERROT1 PIERROT2

	add_link DJAF0 DJAF2
	add_link DJAF1 DJAF2


    bridge_node PIERROT0 eth3 thomas
    bridge_node PIERROT0 eth4 grp6
    bridge_node PIERROT0 eth5 grp5
    bridge_node PIERROT0 eth6 grp8
}


