#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:7::9/128 dev lo

#ip -6 addr add fde4:7:21:01::/64 dev lo
#ip -6 addr add fde4:7:21:14::/64 dev lo

# Assigning IP addr for P1-eth0
ip link set dev DJAF1-eth0 up
ip -6 addr add fde4:7:39::9/64 dev DJAF1-eth0

# Assigning IP addr for P1-eth1
ip link set dev DJAF1-eth1 up
ip -6 addr add fde4:7:910::9/64 dev DJAF1-eth1

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/djaf1.api -i /tmp/djaf1_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/djaf1_ospf.conf -z /tmp/djaf1.api -i /tmp/djaf1_ospf6d.pid -A 127.0.0.1 &

LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/djaf1_bgp.conf -z /tmp/djaf1.api -i /tmp/djaf1_bgpd.pid -A 127.0.0.1

