#! /bin/sh
ldconfig

# Assigning IP addr for lo
#ip -6 addr add fde4:7:20:02::/64 dev lo
#ip -6 addr add fde4:7:20:10::/64 dev lo
#ip -6 addr add fde4:7:20:23::/64 dev lo


# Assigning IP addr for P1-eth0
ip link set dev DJAF0-eth0 up
ip -6 addr add fde4:7:57::7/64 dev DJAF0-eth0

# Assigning IP addr for P1-eth1
ip link set dev DJAF0-eth1 up
ip -6 addr add fde4:7:78::7/64 dev DJAF0-eth1

# Assigning IP addr for P1-eth1
ip link set dev DJAF0-eth2 up
ip -6 addr add fde4:7:79::7/64 dev DJAF0-eth2




# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/djaf0.api -i /tmp/djaf0_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/djaf0_ospf.conf -z /tmp/djaf0.api -i /tmp/djaf0_ospf6d.pid -A 127.0.0.1


