#! /bin/sh
ldconfig

# Assigning IP addr for lo
#ip -6 addr add fde4:7:11:00::/64 dev lo
#ip -6 addr add fde4:7:11:11::/64 dev lo
#ip -6 addr add fde4:7:11:21::/64 dev lo
#ip -6 addr add fde4:7:11:31::/64 dev lo


# Assigning IP addr for P1-eth0
ip link set dev SAMIR1-eth0 up
ip -6 addr add fde4:7:01::1/64 dev SAMIR1-eth0

# Assigning IP addr for P1-eth1
ip link set dev SAMIR1-eth1 up
ip -6 addr add fde4:7:12::1/64 dev SAMIR1-eth1

# Assigning IP addr for P1-eth1
ip link set dev SAMIR1-eth2 up
ip -6 addr add fde4:7:13::1/64 dev SAMIR1-eth2

# Assigning IP addr for P1-eth1
ip link set dev SAMIR1-eth3 up
ip -6 addr add fde4:7:16::1/64 dev SAMIR1-eth3


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/samir1.api -i /tmp/samir1_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/samir1_ospf.conf -z /tmp/samir1.api -i /tmp/samir1_ospf6d.pid -A 127.0.0.1

