#!/bin/bash

sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv6.conf.default.forwarding=1

ip6tables -A INPUT -i lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT


# allow ICMPv6
ip6tables -A INPUT -p ipv6-icmp -j ACCEPT
ip6tables -A FORWARD -p ipv6-icmp -j ACCEPT
ip6tables -A OUTPUT -p ipv6-icmp -j ACCE


#nom des interfaces
#OSPF
ip6tables -A INPUT -i SAMIR1-eth0 -p 89 -j ACCEPT
ip6tables -A OUTPUT -o SAMIR1-eth0 -p 89 -j ACCEPT
ip6tables -A INPUT -i SAMIR1-eth1 -p 89 -j ACCEPT
ip6tables -A OUTPUT -o SAMIR1-eth1 -p 89 -j ACCEPT
ip6tables -A INPUT -i SAMIR1-eth2 -p 89 -j ACCEPT
ip6tables -A OUTPUT -o SAMIR1-eth2 -p 89 -j ACCEPT
ip6tables -A INPUT -i SAMIR1-eth3 -p 89 -j ACCEPT
ip6tables -A OUTPUT -o SAMIR1-eth3 -p 89 -j ACCEPT


#allow BGP
ip6tables -A INPUT -p tcp --dport 179 -j ACCEPT
ip6tables -A OUTPUT -p tcp --dport 179 -j ACCEPT

ip6tables -A INPUT -s 2001:db8::/32 -j DROP
ip6tables -A INPUT -s 2001:10::/28 -j DROP
ip6tables -A INPUT -s 2001:2::/48 -j DROP
ip6tables -A FORWARD -d ::/128 -j DROP


#Block external trafic with our prefix


