#! /bin/sh
ldconfig

# Assigning IP addr for lo
#ip -6 addr add fde4:7:13:01::/64 dev lo
#ip -6 addr add fde4:7:13:12::/64 dev lo
#ip -6 addr add fde4:7:13:22::/64 dev lo
ip link set dev lo up 
ip -6 addr add fde4:7::4/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev SAMIR3-eth0 up
ip -6 addr add fde4:7:14::4/64 dev SAMIR3-eth0


# Assigning IP addr for P1-eth1
ip link set dev SAMIR3-eth1 up
ip -6 addr add fde4:7:24::4/64 dev SAMIR3-eth1


# Assigning IP addr for P1-eth1
ip link set dev SAMIR3-eth2 up
ip -6 addr add fde4:7:34::4/64 dev SAMIR3-eth2



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/samir3.api -i /tmp/samir3_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/samir3_ospf.conf -z /tmp/samir3.api -i /tmp/samir3_ospf6d.pid -A 127.0.0.1
