#! /bin/sh
ldconfig

# Assigning IP addr for lo
ip link set dev lo up
ip -6 addr add fde4:7:deef:beef::3/128 dev lo

# Assigning IP addr for SAMIR2-eth0
ip link set dev SAMIR2-eth0 up
ip -6 addr add fde4:7:baba:23::3/64 dev SAMIR2-eth0
#
# Assigning IP addr for SAMIR2-eth1
ip link set dev SAMIR2-eth1 up
ip -6 addr add fde4:7:baba:38::3/64 dev SAMIR2-eth1
#
# Assigning IP addr for SAMIR2-eth2
ip link set dev SAMIR2-eth2 up
ip -6 addr add fde4:7:baba:39::3/64 dev SAMIR2-eth2
#
# Assigning IP addr for SAMIR2-eth3
ip link set dev SAMIR2-eth3 up
ip -6 addr add fde4:7:baba:34::3/64 dev SAMIR2-eth3
#

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/samir2.api -i /tmp/samir2_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/samir2_ospf.conf -z /tmp/samir2.api -i /tmp/samir2_ospf6d.pid -A 127.0.0.1 &

LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/samir2_bgp.conf -z /tmp/samir2.api -i /tmp/samir2_bgpd.pid -A 127.0.0.1
